### ISSUE TITLE
ll doesn't take the size of the dock into account

### ISSUE THREAD

**Issue by matthiasbalke** [apaszke/termtile#20] opened 2015-08-19 19:25 UTC
I have my dock on the left side of the screen. When I use ll the left half of the screen is used for terminal. so the dock overlaps the iTerm window.

It would be nice if the dock could be taken into account when calculating the available screen size.

**Comment by ezig** [comment] 2015-08-19 20:39
I think this is a general issue with not supporting left/right dock settings. I could look into adding support for this later today the same way that the bottom dock is handled and submit a PR.

**Comment by apaszke** [comment] 2015-08-19 21:16
The problem is that NSScreen reports presence of the dock only if it's on the bottom. Vertical docks can be only detected using AppleScript. I'll add support vertical positions soon, but it probably won't react for scaling (it will be just a hard coded offset). :confused:

**Comment by apaszke** [comment] 2015-08-19 21:16
I'll take a look now. It should be fixed within 2 hours.

**Comment by apaszke** [comment] 2015-08-19 22:14
Uh ok. I've pushed a quick fix for this issue, but the whole dock handling has to be rethinked and rewritten from scratch. I've added a 60px offset for left or right side depending on your settings. Hope this helps!

**Closed as completed by apaszke** 2015-08-19 22:14 UTC

**Comment by matthiasbalke** [comment] 2015-08-26 18:51
thanks works well for the moment

**Comment by apaszke** [comment] 2015-08-26 21:03
Great! It should be even more reliable than in the moment when I've closed this issue.
